In [1]:
import torch


In [47]:

a = torch.tensor ([2.0])   # a tensor with requires_grad = False
t = torch.tensor ([4.0], requires_grad = True)
l = a * t
l = a * t
l.backward()
print(t.grad)
t.grad = None

# a = a**3 + a**2
# a[0] = 1

l = a*t
a = a + torch.tensor([0.4])*a**2
l.backward()
print(t.grad)

t.grad = None
l = a*t
l.backward()
print(t.grad)

tensor([2.])
tensor([2.])
tensor([3.6000])
